        <input type='button' value='Show/hide basic search' onclick="show_hide('basic_search_form');">
        <form id='basic_search_form' method='get' action='#'>
            <fieldset class="card_search">
                <legend>Basic search</legend>
                <ul>
                    <li>
                        <label for='basic_search_name' class="form_title">Card name</label>
                        <input class="card_name" id='basic_search_name' type='text' name='name' value=''>
                    </li>
                    <li>
                        <label for='basic_search_card_type' class="form_title">Card type</label>
                        <select id='basic_search_card_type' name='card_type'>
                            <option value='-2' selected="selected">-</option>
                            <option value='-1'>non-character</option>
                            <option value='0'>Character</option>
                            <option value='1'>Area</option>
                            <option value='2'>Item</option>
                            <option value='3'>Event</option>
                            
                        </select>
                    </li>
                    <li>
                        <label for='basic_search_name' class="form_title">Cost</label>
                        <select id='basic_search_cost_type' name='cost_type'>
                            <option value="0" selected="selected">-</option>
                            <option value="1">payable by:</option>
                            <option value="2">is exactly:</option>
                        </select>
                        <label for="basic_search_cost_snow"><img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"></label>
                        <select id='basic_search_cost_snow' name='cost_snow'>
                            <option value='0'>0</option>
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='7'>7</option>
                            <option value='8'>8</option>
                            <option value='9'>9</option>
                            <option value='10'>10</option>
                            <option value='11'>11</option>
                            <option value='12'>12</option>
                        </select>
                        <label for="basic_search_cost_moon"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"></label>
                        <select id='basic_search_cost_moon' name='cost_moon'>
                            <option value='0'>0</option>
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='7'>7</option>
                            <option value='8'>8</option>
                            <option value='9'>9</option>
                            <option value='10'>10</option>
                            <option value='11'>11</option>
                            <option value='12'>12</option>
                        </select>
                        <label for="basic_search_cost_lightning"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"></label>
                        <select id='basic_search_cost_lightning' name='cost_lightning'>
                            <option value='0'>0</option>
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='7'>7</option>
                            <option value='8'>8</option>
                            <option value='9'>9</option>
                            <option value='10'>10</option>
                            <option value='11'>11</option>
                            <option value='12'>12</option>
                        </select>
                        <label for="basic_search_cost_flower"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"></label>
                        <select id='basic_search_cost_flower' name='cost_flower'>
                            <option value='0'>0</option>
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='7'>7</option>
                            <option value='8'>8</option>
                            <option value='9'>9</option>
                            <option value='10'>10</option>
                            <option value='11'>11</option>
                            <option value='12'>12</option>
                        </select>
                        <label for="basic_search_cost_sun"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif"></label>
                        <select id='basic_search_cost_sun' name='cost_sun'>
                            <option value='0'>0</option>
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='7'>7</option>
                            <option value='8'>8</option>
                            <option value='9'>9</option>
                            <option value='10'>10</option>
                            <option value='11'>11</option>
                            <option value='12'>12</option>
                        </select>
                        <label for="basic_search_cost_star"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"></label>
                        <select id='basic_search_cost_star' name='cost_star'>
                            <option value='0'>0</option>
                            <option value='1'>1</option>
                            <option value='2'>2</option>
                            <option value='3'>3</option>
                            <option value='4'>4</option>
                            <option value='5'>5</option>
                            <option value='6'>6</option>
                            <option value='7'>7</option>
                            <option value='8'>8</option>
                            <option value='9'>9</option>
                            <option value='10'>10</option>
                            <option value='11'>11</option>
                            <option value='12'>12</option>
                        </select>
                    </li>
                    <li>
                        <label for='basic_search_name' class="form_title">Ex</label>
                        <select id="basic_search_ex_operator" name="ex_operator">
                            <option value="1" selected="selected">≥</option>
                            <option value="0">=</option>
                            <option value="-1">≤</option>
                        </select>
                        <select id="basic_search_ex" name="ex">
                            <option value="0">0</option>
                            <option value="0">1</option>
                            <option value="0">2</option>
                            <option value="0">3</option>
                        </select>
                    </li>
                    <li>
                        <label class="form_title">Element</label>
                        <select id='basic_search_element_type' name='element_type'>
                            <option value='0'>-</option>
                            <option value='1'>has:</option>
                            <option value='2'>is:</option>
                        </select>
                        <label for="basic_search_element_snow"><img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"></label><input type="checkbox" id="basic_search_element_snow" name="element_snow">
                        <label for="basic_search_element_moon"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"></label><input type="checkbox" id="basic_search_element_moon" name="element_moon">
                        <label for="basic_search_element_lightning"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"></label><input type="checkbox" id="basic_search_element_lightning" name="element_lightning">
                        <label for="basic_search_element_flower"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"></label><input type="checkbox" id="basic_search_element_flower" name="element_flower">
                        <label for="basic_search_element_sun"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif"></label><input type="checkbox" id="basic_search_element_sun" name="element_sun">
                    </li>
                    <li>
                        <label for='basic_search_text' class="form_title">Text contains</label>
                        <input class="card_text" id='basic_search_text' type='text' name='text' value=''>
                    </li>
                </ul>
            </fieldset>
        </form>
        <table class="card_results">
            <thead>
                <colgroup class="card_result_columns">
                    <col class="card_id">
                    <col class="card_name">
                    <col class="card_sets">
                    <col class="card_cost">
                    <col class="card_ex">
                    <col class="card_element">
                    <col class="card_spots">
                    <col class="card_ap">
                    <col class="card_dp">
                    <col class="card_sp">
                </colgroup>
                <tr class="card_result_columns">
                    <th class="card_id" id="card_result_title_0" onclick="reorder_table('card_result', 0)">Card ID</th>
                    <th class="card_name" id="card_result_title_1" onclick="reorder_table('card_result', 1)">Name</th>
                    <th class="card_sets" id="card_result_title_9" onclick="reorder_table('card_result', 2)">Card sets</th>
                    <th class="card_cost" id="card_result_title_2" onclick="reorder_table('card_result', 3)">Cost</th>
                    <th class="card_ex" id="card_result_title_3" onclick="reorder_table('card_result', 4)">Ex</th>
                    <th class="card_element" id="card_result_title_4" onclick="reorder_table('card_result', 5)">Element</th>
                    <th class="card_spots" id="card_result_title_5" onclick="reorder_table('card_result', 6)">FL</th>
                    <th class="card_ap" id="card_result_title_6" onclick="reorder_table('card_result', 7)">AP</th>
                    <th class="card_dp" id="card_result_title_7" onclick="reorder_table('card_result', 8)">DP</th>
                    <th class="card_sp" id="card_result_title_8" onclick="reorder_table('card_result', 9)">SP</th>
                </tr>
            </thead>
            
            
            <tbody>
                <?php foreach ($this->cards as $card): ?>
                <tr id="card_result_<?= $card['id'] ?>" class="character">
                    <td onmouseover="display_card(this, event);" onmouseout="hide_card(this, event);" onmousemove="update_card_attachment_position(event)"><?= $card['cid'] ?></td>
                    <td onmouseover="display_card(this, event);" onmouseout="hide_card(this, event);" onmousemove="update_card_attachment_position(event)"><?= $card['name_jp'] ?></td>
                    <td>Coming soon...</td>
                    <td><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"></td>
                    <td>2</td>
                    <td><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"></td>
                    <td>
                        <div class="card_spot_row">
                            <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1"><img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1"><img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        </div>
                        <div class="card_spot_row">
                            <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1"><img src="<?php echo $this->basePath() ?>/img/spot-off.gif" alt="0"><img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        </div>
                    </td>
                    <td>3</td>
                    <td>2</td>
                    <td>1</td>
                </tr>
                <?php endforeach ?>
                <tr id="card_result_0" class="character">
                    <td onmouseover="display_card(this, event);" onmouseout="hide_card(this, event);" onmousemove="update_card_attachment_position(event)">CH-0409</td>
                    <td onmouseover="display_card(this, event);" onmouseout="hide_card(this, event);" onmousemove="update_card_attachment_position(event)">Tohno Akiha</td>
                    <td>Type-Moon 1.0</td>
                    <td><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"></td>
                    <td>2</td>
                    <td><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"></td>
                    <td>
                        <div class="card_spot_row">
                            <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1"><img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1"><img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        </div>
                        <div class="card_spot_row">
                            <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1"><img src="<?php echo $this->basePath() ?>/img/spot-off.gif" alt="0"><img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        </div>
                    </td>
                    <td>3</td>
                    <td>2</td>
                    <td>1</td>
                </tr>
                <tr id="card_result_1" class="event">
                    <td onmouseover="display_card(this, event);" onmouseout="hide_card(this, event);" onmousemove="update_card_attachment_position(event)">EV-0207</td>
                    <td onmouseover="display_card(this, event);" onmouseout="hide_card(this, event);" onmousemove="update_card_attachment_position(event)">Big Mistake</td>
                    <td>Type-Moon 2.0</td>
                    <td style="width:120px;">
                        <img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"><img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif">
                    </td>
                    <td>0</td>
                    <td>
                        <img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif">
                    </td>
                    <td>
                        &nbsp;
                    </td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tbody>
        </table>
