<!doctype html>
<html>
  <head>
    <?php echo $this->headTitle('Lycee TCG Card Database') ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/style.css">
  <meta charset="utf-8">
  <script type='text/javascript' src='<?php echo $this->basePath() ?>/jquery-1.3.2.js'></script>
  <script type='text/javascript' src='<?php echo $this->basePath() ?>/js.js'></script>
  </head>
  <body>
    
    <div id='header'>
        
    </div>
    <div id='nav'>
        <ul class="nav left">
            <li><a href='index.php?p=1'>About</a></li>
            <li><a href='index.php'>News</a></li>
            <li><a href='index.php?p=2'>Card search</a></li>
            <li><a href='http://forums.akiba-ch.com/viewforum.php?f=4'>Akihabara Forums</a></li>
        </ul>
        <ul class="nav right">
            <li><div><span>Welcome, <span class='nick'>amcsi</span>!</span></div></li>
            <li><a href='index.php?p=5'>Settings</a></li>
            <li><a href='index.php'>Logout</a></li>
        </ul>
    </div>
    
    <div id='content'>
        <?php echo $this->content ?>
    </div>
    <div id='footer'>
        <div class="optimized">This website is optimized for the following browsers: <span class="browser">Opera 10+</span>, <span class="browser">FireFox 3.5+</span>, <span class="browser">Internet Explorer 7+</span>; and the resolution <span class="resolution">800x600</span>
        </div>
        <div>
            <span class="coding"><span class="property">Coding:</span> <a href="mailto:amcsi@mailbox.hu">amcsi</a></span><br>
            <span class="design"><span class="property">Design:</span> <a href="mailto:amcsi@mailbox.hu">amcsi</a></span>
        </div>
    </div>
    
    
    
    
    
    
    
    
    <div id='hidden'>
        <div class="hidden card_js character" id="card_js_0">
            <div class="card_js_image">
                <img alt="CH-0409 Tohno Akiha" src="<?php echo $this->basePath() ?>/img/cards/middle/tm01/CH-0409-m.jpg">
            </div>
            <div class="card_js_details">
                <div class="card_js_id card_js_detail_left">
                    <span>CH-0409</span>
                </div>
                <div class="card_js_sets">
                    <span>Type-Moon 1.0</span>
                </div>
                <div class="card_js_name">
                    <span class="card_name card_js_detail_left">Tohno Akiha</span>
                </div>
                <div class="card_js_name_jap">
                    <span class="card_name jap">遠野秋葉</span>
                </div>
                <div class="card_js_ex card_js_detail_left">
                    <span>
                        <strong>Ex:</strong> 2
                        <img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif">
                    </span>
                </div>
                <div class="card_js_cost">
                    <span>
                        <img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"><img alt='star' src="<?php echo $this->basePath() ?>/img/star.gif"> 
                    </span>
                </div>
                <div class="card_js_ap_dp_sp card_js_detail_left">
                    <div class='left ap'>3</div>
                    <div class='left dp'>2</div>
                    <div class='left sp'>1</div>
                </div>
                <div class="card_js_spots">
                    <div class="card_spot_row">
                        <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                    </div>
                    <div class="card_spot_row">
                        <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                        <img src="<?php echo $this->basePath() ?>/img/spot-off.gif" alt="0">
                        <img src="<?php echo $this->basePath() ?>/img/spot-on.gif" alt="1">
                    </div>
                </div>
                <div class="card_js_text card_js_detail_full">
                    <p class="ability_name">
                        <span>
                            Plunder:
                            <img src="<?php echo $this->basePath() ?>/img/0.gif" alt="0">
                        </span>
                    </p>
                    <p class="card_text">
                        <span>
                            <span class="target">This character</span> will gain all the basic abilities of an <span class="target">opponent character in the same column as this character</span>. You can not gain a basic ability that this character has already gained. (Can be only used once every turn)
                        </span>
                    </p>
                </div>
            </div>
        </div>
        
        <div class="hidden card_js event" id="card_js_1">
            <div class="card_js_image">
                <img alt="CH-0409 Tohno Akiha" src="<?php echo $this->basePath() ?>/img/cards/middle/tm02/EV-0207-m.jpg">
            </div>
            <div class="card_js_details">
                <div class="card_js_id card_js_detail_left">
                    <span>EV-0207</span>
                </div>
                <div class="card_js_sets">
                    <span>Type-Moon 2.0</span>
                </div>
                <div class="card_js_name">
                    <span class="card_name card_js_detail_left">Big Mistake</span>
                </div>
                <div class="card_js_name_jap">
                    <span class="card_name jap">大失敗</span>
                </div>
                <div class="card_js_ex card_js_detail_left">
                    <span>
                        <strong class="ex">Ex</strong> <span class="ex">0</span>
                        <img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif">
                    </span>
                </div>
                <div class="card_js_cost">
                    <span>
                        <img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"><img alt='snow' src="<?php echo $this->basePath() ?>/img/snow.gif"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"><img alt='moon' src="<?php echo $this->basePath() ?>/img/moon.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='lightning' src="<?php echo $this->basePath() ?>/img/lightning.gif"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"><img alt='flower' src="<?php echo $this->basePath() ?>/img/flower.gif"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif"><img alt='sun' src="<?php echo $this->basePath() ?>/img/sun.gif">
                    </span>
                </div>
                <div class="card_js_text card_js_detail_full">
                    <p class="card_text">
                        <span>
                            Discard all cards in <span class="target">your opponent's hand</span>. For every card discarded, discard 3 cards from your deck.
                        </span>
                    </p>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>
