<!doctype html>
<html>
  <head>
    <?php echo $this->headTitle('Lycee TCG Card Database') ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/style.css">
  <meta charset="utf-8">
  <script type='text/javascript' src='<?php echo $this->basePath() ?>/jquery-1.3.2.js'></script>
  <script type='text/javascript' src='<?php echo $this->basePath() ?>/js.js'></script>
  </head>
  <body>
    
    <div id='header'>
        
    </div>
    <div id='nav'>
        <ul class="nav left">
            <li><a href='index.php?p=1'>About</a></li>
            <li><a href='index.php'>News</a></li>
            <li><a href='index.php?p=2'>Card search</a></li>
            <li><a href='http://forums.akiba-ch.com/viewforum.php?f=4'>Akihabara Forums</a></li>
        </ul>
        <ul class="nav right">
            <li><div><span>Welcome, <span class='nick'>amcsi</span>!</span></div></li>
            <li><a href='index.php?p=5'>Settings</a></li>
            <li><a href='index.php'>Logout</a></li>
        </ul>
    </div>
    
    <div id='content'>
        <?php echo $this->content ?>
    </div>
    <div id='footer'>
        <div class="optimized">This website is optimized for the following browsers: <span class="browser">Opera 10+</span>, <span class="browser">FireFox 3.5+</span>, <span class="browser">Internet Explorer 7+</span>; and the resolution <span class="resolution">800x600</span>
        </div>
        <div>
            <span class="coding"><span class="property">Coding:</span> <a href="mailto:amcsi@mailbox.hu">amcsi</a></span><br>
            <span class="design"><span class="property">Design:</span> <a href="mailto:amcsi@mailbox.hu">amcsi</a></span>
        </div>
    </div>
    
    
    
    
    
    
    
  </body>
</html>
