<!doctype html>
<html>
  <head>
    <?php echo $this->headTitle('Lycee TCG Card Database') ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath() ?>/style.css">
  <meta charset="utf-8">
    <script type='text/javascript' src='<?php echo $this->basePath() ?>/jquery-1.3.2.js'></script>
    <script type='text/javascript' src='<?php echo $this->basePath() ?>/js.js'></script>

</head>
  <body>
    <?php if (!empty($this->google_analytics['code'])): ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?= $this->google_analytics['code'] ?>', '<?= $this->google_analytics['domain'] ?>');
        ga('send', 'pageview');
    </script>
    <?php endif ?>
    
    <div id='header'>
        
    </div>
    <div id='nav'>
        <ul class="nav left">
            <li><a href='index.php?p=1'>About</a></li>
            <li><a href='index.php'>News</a></li>
            <li><a href='index.php?p=2'>Card search</a></li>
            <li><a href='http://forums.akiba-ch.com/viewforum.php?f=4'>Akihabara Forums</a></li>
        </ul>
        <ul class="nav right">
            <li><div><span>Welcome, <span class='nick'>amcsi</span>!</span></div></li>
            <li><a href='index.php?p=5'>Settings</a></li>
            <li><a href='index.php'>Logout</a></li>
        </ul>
    </div>
    
    <div id='content'>
        <?php echo $this->content ?>
    </div>
    <div id='footer'>
        <div class="optimized">This website is optimized for the following browsers: <span class="browser">Opera 10+</span>, <span class="browser">FireFox 3.5+</span>, <span class="browser">Internet Explorer 7+</span>; and the resolution <span class="resolution">800x600</span>
        </div>
        <div>
            <span class="coding"><span class="property">Coding:</span> <a href="mailto:amcsi@mailbox.hu">amcsi</a></span><br>
            <span class="design"><span class="property">Design:</span> <a href="mailto:amcsi@mailbox.hu">amcsi</a></span>
        </div>
        <?php if (isset($this->amysqlQueriesData)): ?>
            <div>MySQL query information:</div>
            <?php if ($this->amysqlQueriesData): ?>
            <table class="queryInfoTable">
                <tr>
                    <th class="no">No.</th>
                    <th class="query">Query</th>
                    <th class="time">Time</th>
                </tr>
                <?php foreach ($this->amysqlQueriesData as $index => $row): ?>
                <tr>
                    <td>#<?= $index ?></td>
                    <td><?= $this->escapeHtml($row['query']) ?></td>
                    <td><?= $this->escapeHtml($row['time']) ?></td>
                </tr>
                <?php endforeach ?>
            </table>
            <?php else: ?>
            <div>No MySQL queries were run</div>
            <?php endif ?>

        <?php endif ?>
    </div>
    
    
    
    
    
    
    
  </body>
</html>
